import type { Metadata } from "next";
import { Nunito, Nunito_Sans} from "next/font/google";
import "./globals.css";
import clsx from "clsx";


const nunito = Nunito({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable:'--font-nunito'
});
const nunito_Sans = Nunito_Sans({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable:'--font-nunito-sans'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={clsx(nunito.variable, nunito_Sans.variable)}>{children}</body>
    </html>
  );
}
